### ISSUE TITLE
Adding a clear button

### ISSUE THREAD

**Issue by MurtazaMister** [MurtazaMister/Competitive-Trainer#1]
In the codeforces tab of the extension, add a <b>Clear all</b> button beside <b>Go!</b> button to clear all the selected topics.

**Comment by pramod74** [comment]
Hi @MurtazaMister,

I would like to give this issue a shot. Request you to assign it to me.

**Comment by MurtazaMister** [comment]
Sure @pramod74, go ahead :)

**Comment by pramod74** [comment]
Thanks @MurtazaMister. I have submitted a PR. Kindly review.

**Comment by MurtazaMister** [comment]
Well done 💯 @pramod74 :)

**Comment by pramod74** [comment]
> Well done 💯 @pramod74 :)

Thanks, @MurtazaMister . I am glad I could help. :)
